bifrost:
    image: sgehrman/stellar-bifrost
    container_name: stellar-bifrost
    volumes:
      - ~/bifrost-testnet:/opt/bifrost
    restart: unless-stopped
    environment:
      MASTER_PUBLIC_KEY: "xpub6C79eBsW2XQbzfXFsRv51Lac6Ckx5nyqf9cUmFr1fuAEHGXmpq8oPNMqCpH1jTdwP3s5SD644R8KK4cVytk9Jxcxcb7JsfNxcGNRbG5q4pq"
      BIFROST_BITCOIN_RPC_SERVER: "http://stellarkit.io:18332"
      RPC_USER: "stellar"
      RPC_PASS: "password"
      TESTNET: "true"
      MINIMUM_VALUE_BTC:  "0.00001"
      BIFROST_ETHEREUM_RPC_SERVER: "http://stellarkit.io:8545"
      NETWORK_ID: "3"
      MINIMUM_VALUE_ETH: "0.00001"
      BIFROST_STELLAR_ISSUER_PUBLIC_KEY: "GD5H2WSHTWVTZI5BR3V5XTRBCFDMEOKFMXR4Y4PU337K7WS55UAADI5T"
      BIFROST_STELLAR_SIGNER_SECRET_KEY: "SD4DFZ433RUGNCMCG4JGWK47R5KOHQOS4T5LXGLGBLY7ZLBUZQTTONVQ"
      TOKEN_ASSET_CODE: "LMB"
      NEEDS_AUTHORIZE: "true"
      BIFROST_STELLAR_HORIZON: "https://stellarkit.io:8000"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
      BIFROST_DB_TYPE: "postgres"
      BIFROST_DB_DSN: "postgres://stellar:password@localhost:8000?sslmode=disable"
    ports:
      - 8100:8000/tcp
